### ISSUE TITLE
Error with apostrophes

### ISSUE THREAD

**Issue by fermo111** [ema/pycodicefiscale#7]
There is an error when the last name is 3 characters long and contains an apostrophe. E.g.: FO'

**Comment by valholl** [comment]
This is the error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/codicefiscale.py", line 161, in build
    output = __surname_triplet(surname) + __name_triplet(name)
  File "/usr/lib/python2.7/dist-packages/codicefiscale.py", line 94, in __surnam
e_triplet
    return __common_triplet(input_string, consonants, vowels)
  File "/usr/lib/python2.7/dist-packages/codicefiscale.py", line 71, in __common
_triplet
    output += vowels.pop(0)
IndexError: pop from empty list
```

And also happens when the surname is just one character long.

(I will look into it more in detail in the next few days, and possibly propose a patch.)
